### ISSUE TITLE
Make fails with "GOPATH is undefined"

### ISSUE THREAD

**Issue by thomask77** [maximeh/mkpimage#2]
Testing under Ubuntu 16.10, Steps to reproduce:

```bash
$ sudo apt install golang
$ git clone https://github.com/maximeh/mkpimage
$ cd mkpimage
$ make
Makefile:37: *** GOPATH is undefined.  Stop.
```

Could you please add an explanation to the README file?

**Comment by maximeh** [comment]
Hey,

Thanks for bringing this to my attention. I pushed a "fix" in the Makefile. Basically, the Makefile will use the './third-party' directory and not ask anything from the user.
It's more convenient, if there's something wrong about it because the GOPATH should be shared among all projects or something like that, I'll change this with some better code.

Thanks again !
